[book]
title = "Nibbāna - The Mind Stilled"
authors = ["Bhikkhu Kaṭukurunde Ñāṇananda"]
language = "en"
multilingual = false
src = "manuscript/markdown"

[build]
build-dir = "book"
create-missing = true

[output.epub]
additional-css = ["assets/stylesheets/output-epub.css"]
epub-version = 3
use-default-css = false
no-section-label = true
footnote-backrefs = true
curly-quotes = true
cover-image = "desktop-cover.jpg"
additional-resources = ["manuscript/markdown/assets/images/moonstone-1-crop.jpg", "manuscript/markdown/assets/images/moonstone-2-crop.jpg", "manuscript/markdown/assets/images/moonstone-3-crop.jpg", "manuscript/markdown/assets/images/moonstone-4-crop.jpg", "manuscript/markdown/assets/images/moonstone-5-crop.jpg", "manuscript/markdown/assets/images/moonstone-6-crop.jpg", "manuscript/markdown/assets/images/moonstone-7-crop.jpg", "manuscript/markdown/assets/images/moonstone-8-crop.jpg", "manuscript/markdown/assets/images/moonstone-9-crop.jpg", "manuscript/markdown/assets/images/moonstone-10-crop.jpg", "manuscript/markdown/assets/images/moonstone-11-crop.jpg", "manuscript/markdown/assets/images/moonstone-12-crop.jpg", "manuscript/markdown/assets/images/moonstone-13-crop.jpg", "manuscript/markdown/assets/images/moonstone-14-crop.jpg", "manuscript/markdown/assets/images/moonstone-15-crop.jpg", "manuscript/markdown/assets/images/moonstone-16-crop.jpg", "manuscript/markdown/assets/images/moonstone-17-crop.jpg", "manuscript/markdown/assets/images/moonstone-18-crop.jpg", "manuscript/markdown/assets/images/moonstone-19-crop.jpg", "manuscript/markdown/assets/images/moonstone-20-crop.jpg", "manuscript/markdown/assets/images/moonstone-21-crop.jpg", "manuscript/markdown/assets/images/moonstone-22-crop.jpg", "manuscript/markdown/assets/images/moonstone-23-crop.jpg", "manuscript/markdown/assets/images/moonstone-24-crop.jpg", "manuscript/markdown/assets/images/moonstone-25-crop.jpg", "manuscript/markdown/assets/images/moonstone-26-crop.jpg", "manuscript/markdown/assets/images/moonstone-27-crop.jpg", "manuscript/markdown/assets/images/moonstone-28-crop.jpg", "manuscript/markdown/assets/images/moonstone-29-crop.jpg", "manuscript/markdown/assets/images/moonstone-30-crop.jpg", "manuscript/markdown/assets/images/moonstone-31-crop.jpg", "manuscript/markdown/assets/images/moonstone-32-crop.jpg", "manuscript/markdown/assets/images/moonstone-white.jpg",]
