[book]
title = "Nibbāna - The Mind Stilled"
authors = ["Bhikkhu K. Ñāṇananda"]
language = "en"
multilingual = false
src = "manuscript/markdown"

[build]
build-dir = "book"
create-missing = true

[output.html]
additional-css = ["assets/stylesheets/output-html.css"]
smart-punctuation = true
footnote-backrefs = true
no-section-label = true
site-url = "https://seeingthroughthenet.github.io/nibbana-the-mind-stilled/"

[output.html.fold]
enable = true
level = 2

